# Generated by Django 3.1.5 on 2021-02-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadfree', '0003_auto_20210210_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
