# Generated by Django 3.1.5 on 2021-02-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadfree', '0004_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='message',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='subject',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
